# Gitpod'a diyoruz ki: Workspace'i standart imajla değil,
# bizim sağladığımız bu Dockerfile ile oluştur.
image:
  file: .gitpod.Dockerfile

tasks:
  - name: Docker Daemon'u Başlat
    command: |
      # Root yetkisiyle Docker servisini arka planda başlatıyoruz.
      # Çıktıları /dev/null'a göndererek terminali kirletmesini engelliyoruz.
      sudo dockerd > /dev/null 2>&1 &
      
      # Daemon'un başlaması için bekliyoruz.
      sleep 5
      
      echo -e "\n\033[32mDocker hazır. Bu terminali kullanabilirsin.\033[0m"
      # Shell'i açık tut ki terminal kapanmasın.
      bash