# Bu satır, workspace'e Docker ve iptables gibi
# sistem seviyesi araçları kullanma yetkisi verir.
# Bu, "Permission denied (you must be root)" hatasını çözer.
privileged: true

tasks:
  - name: Docker'ı Başlat ve Ayarla
    init: |
      # Daemon'u arka planda başlat. Ayrıcalıklı modda bu sorunsuz çalışacaktır.
      dockerd > /dev/null 2>&1 &
      # Daemon'un başlaması için birkaç saniye bekle.
      sleep 5
    command: |
      # İzinleri ayarla ki her seferinde sudo yazmak zorunda kalma.
      sudo chmod 666 /var/run/docker.sock
      echo -e "\n\033[32mDocker hazır! 'docker ps' komutuyla test edebilirsin.\033[0m"